### ISSUE TITLE
NFT: Additional Validation tests (Overview)

### ISSUE THREAD

**Issue by cstml** [mlabs-haskell/plutus-use-cases#233]
Issue that is meant to provide an overview of the additional Validation/Minting Policy necessary conditions to be added: 

- [ ] Test that all the used tokens are returned #231 #230
- [ ] Test that all the returned tokens have corresponding `Datums` in the same `UTXO` #230
- [ ] Test that the correct number/type of `Tokens` is used for each operation #231#230 
- [ ] Test that initialisation is done according to spec #211
